const express = require("express");
const app = express();
const http = require("http");
const server = http.createServer(app);
const { Server } = require("socket.io");
const io = new Server(server);
var gphoto2 = require("gphoto2");
var GPhoto = new gphoto2.GPhoto2();

var camera;

app.use("/", express.static("www"));

GPhoto.list(function (list) {
  if (list.length === 0) return;
  camera = list[0];
  console.log("Found", camera.model);
});

GPhoto.setLogLevel(1);
GPhoto.on("log", function (level, domain, message) {
  console.log(domain, message);
});

io.on("connection", (socket) => {
  console.log("a user connected !");
  socket.on("settings", async () => {
    /*await camera.getConfig(function (er, settings) {
      socket.emit("res_settings", settings);
    });*/

    socket.emit("res_settings", data);
  });
});

server.listen(6500, () => {
  console.log("listening on localhost:6500");
});

var data.main = {
  type: "section",
  label: "Camera and Driver Configuration",
  children: {
    actions: {
      type: "section",
      label: "Camera Actions",
      children: {
        autofocusdrive: {
          label: "Drive Nikon DSLR Autofocus",
          type: "toggle",
          value: 0,
        },
        bulb: {
          label: "Bulb Mode",
          type: "toggle",
          value: 2,
        },
        changeafarea: {
          label: "Set Nikon Autofocus area",
          type: "string",
          value: "0x0",
        },
        controlmode: {
          label: "Set Nikon Control Mode",
          type: "string",
          value: "0",
        },
        manualfocusdrive: {
          label: "Drive Nikon DSLR Manual focus",
          type: "range",
          value: 0,
          max: 32767,
          min: -32767,
          step: 1,
        },
        opcode: {
          label: "PTP Opcode",
          type: "string",
          value: "0x1001,0xparam1,0xparam2",
        },
        viewfinder: {
          label: "Nikon Viewfinder",
          type: "toggle",
          value: 0,
        },
      },
    },
    capturesettings: {
      type: "section",
      label: "Capture Settings",
      children: {
        aebracketingcount: {
          label: "AE Bracketing Count",
          type: "range",
          value: 1,
          max: 3,
          min: 1,
          step: 1,
        },
        aebracketingpattern: {
          label: "AE Bracketing Pattern",
          type: "choice",
          value: "3 images (normal and 2 unders)",
          choices: [
            "2 images (normal and under)",
            "2 images (normal and over)",
            "3 images (normal and 2 unders)",
          ],
        },
        aebracketingstep: {
          label: "AE Bracketing Step",
          type: "choice",
          value: "Unknown value 0007",
          choices: [
            "1/3 EV",
            "1/2 EV",
            "2/3 EV",
            "1 EV",
            "2 EV",
            "3 EV",
            "Unknown value 0006",
            "Unknown value 0007",
          ],
        },
        aelaflmode: {
          label: "AE-L/AF-L Mode",
          type: "choice",
          value: "AF Lock Only",
          choices: [
            "AE/AF Lock",
            "AE Lock only",
            "AF Lock Only",
            "AF Lock Hold",
            "AF On",
            "Flash Level Lock",
          ],
        },
        "af-area-illumination": {
          label: "AF Area Illumination",
          type: "choice",
          value: "On",
          choices: ["Auto", "Off", "On"],
        },
        afbeep: {
          label: "AF Beep Mode",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        assistlight: {
          label: "Assist Light",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        autofocusarea: {
          label: "Auto Focus Area",
          type: "choice",
          value: "Top",
          choices: [
            "Top",
            "Bottom",
            "Left",
            "Right",
            "Unknown value 0005",
            "Unknown value 0006",
            "Unknown value 0007",
            "Unknown value 0008",
            "Unknown value 0009",
            "Unknown value 000a",
            "Unknown value 000b",
          ],
        },
        autowhitebias: {
          label: "Auto White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        bracketing: {
          label: "Bracketing",
          type: "choice",
          value: "On",
          choices: ["On", "Off"],
        },
        bracketorder: {
          label: "Bracket Order",
          type: "choice",
          value: "MTR > Under",
          choices: ["MTR > Under", "Under > MTR"],
        },
        bracketset: {
          label: "Bracket Set",
          type: "choice",
          value: "AE & Flash",
          choices: [
            "AE & Flash",
            "AE only",
            "Flash only",
            "WB bracketing",
            "ADL bracketing",
          ],
        },
        burstnumber: {
          label: "Burst Number",
          type: "range",
          value: 1,
          max: 100,
          min: 1,
          step: 1,
        },
        capturemode: {
          label: "Still Capture Mode",
          type: "choice",
          value: "Single Shot",
          choices: [
            "Single Shot",
            "Burst",
            "Continuous Low Speed",
            "Timer",
            "Quick Response Remote",
            "Delayed Remote",
          ],
        },
        centerweightsize: {
          label: "Center Weight Area",
          type: "choice",
          value: "8 mm",
          choices: ["6 mm", "8 mm", "10 mm"],
        },
        cloudywhitebias: {
          label: "Cloudy White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        daylightwhitebias: {
          label: "Daylight White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        dlighting: {
          label: "Active D-Lighting",
          type: "choice",
          value: "Off",
          choices: ["Extra high", "High", "Normal", "Low", "Off", "Auto"],
        },
        evstep: {
          label: "EV Step",
          type: "choice",
          value: "1/3",
          choices: ["1/3", "1/2", "Unknown value 0002"],
        },
        exposurecompensation: {
          label: "Exposure Compensation",
          type: "choice",
          value: "0",
          choices: [
            "-5",
            "-4.666",
            "-4.333",
            "-4",
            "-3.666",
            "-3.333",
            "-3",
            "-2.666",
            "-2.333",
            "-2",
            "-1.666",
            "-1.333",
            "-1",
            "-0.666",
            "-0.333",
            "0",
            "0.333",
            "0.666",
            "1",
            "1.333",
            "1.666",
            "2",
            "2.333",
            "2.666",
            "3",
            "3.333",
            "3.666",
            "4",
            "4.333",
            "4.666",
            "5",
          ],
        },
        exposurecompensation2: {
          label: "Exposure Compensation",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        exposuredelaymode: {
          label: "Exposure Delay Mode",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        exposurelock: {
          label: "Exposure Lock",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        exposuremetermode: {
          label: "Exposure Metering Mode",
          type: "choice",
          value: "Multi Spot",
          choices: ["Center Weighted", "Multi Spot", "Center Spot"],
        },
        expprogram: {
          label: "Exposure Program",
          type: "choice",
          value: "M",
          choices: [
            "M",
            "P",
            "A",
            "S",
            "Auto",
            "Portrait",
            "Landscape",
            "Macro",
            "Sports",
            "Night Portrait",
            "Night Landscape",
          ],
        },
        "f-number": {
          label: "F-Number",
          type: "choice",
          value: "f/6.3",
          choices: [
            "f/3.5",
            "f/4",
            "f/4.5",
            "f/5",
            "f/5.6",
            "f/6.3",
            "f/7.1",
            "f/8",
            "f/9",
            "f/10",
            "f/11",
            "f/13",
            "f/14",
            "f/16",
            "f/18",
            "f/20",
            "f/22",
          ],
        },
        filenrsequencing: {
          label: "File Number Sequencing",
          type: "choice",
          value: "On",
          choices: ["On", "Off"],
        },
        flashcommandacompensation: {
          label: "Flash Command A Compensation",
          type: "choice",
          value: "0.0",
          choices: [
            "-3.0",
            "-2.7",
            "-2.3",
            "-2.0",
            "-1.7",
            "-1.3",
            "-1.0",
            "-0.7",
            "-0.3",
            "0.0",
            "0.3",
            "0.7",
            "1.0",
            "1.3",
            "1.7",
            "2.0",
            "2.3",
            "2.7",
            "3.0",
          ],
        },
        flashcommandamode: {
          label: "Flash Command A Mode",
          type: "choice",
          value: "TTL",
          choices: ["TTL", "Auto Aperture", "Manual", "Off"],
        },
        flashcommandavalue: {
          label: "Flash Command A Value",
          type: "choice",
          value: "Full",
          choices: [
            "Full",
            "1/1.3",
            "1/1.7",
            "1/2",
            "1/2.5",
            "1/3.2",
            "1/4",
            "1/5",
            "1/6.4",
            "1/8",
            "1/10",
            "1/13",
            "1/16",
            "1/20",
            "1/25",
            "1/32",
            "1/40",
            "1/50",
            "1/64",
            "1/80",
            "1/100",
            "1/128",
          ],
        },
        flashcommandbcompensation: {
          label: "Flash Command B Compensation",
          type: "choice",
          value: "0.0",
          choices: [
            "-3.0",
            "-2.7",
            "-2.3",
            "-2.0",
            "-1.7",
            "-1.3",
            "-1.0",
            "-0.7",
            "-0.3",
            "0.0",
            "0.3",
            "0.7",
            "1.0",
            "1.3",
            "1.7",
            "2.0",
            "2.3",
            "2.7",
            "3.0",
          ],
        },
        flashcommandbmode: {
          label: "Flash Command B Mode",
          type: "choice",
          value: "TTL",
          choices: ["TTL", "Auto Aperture", "Manual", "Off"],
        },
        flashcommandbvalue: {
          label: "Flash Command B Value",
          type: "choice",
          value: "Full",
          choices: [
            "Full",
            "1/1.3",
            "1/1.7",
            "1/2",
            "1/2.5",
            "1/3.2",
            "1/4",
            "1/5",
            "1/6.4",
            "1/8",
            "1/10",
            "1/13",
            "1/16",
            "1/20",
            "1/25",
            "1/32",
            "1/40",
            "1/50",
            "1/64",
            "1/80",
            "1/100",
            "1/128",
          ],
        },
        flashcommandchannel: {
          label: "Flash Command Channel",
          type: "choice",
          value: "1",
          choices: ["1", "2", "3", "4"],
        },
        flashcommandselfcompensation: {
          label: "Flash Command Self Compensation",
          type: "choice",
          value: "0.0",
          choices: [
            "-3.0",
            "-2.7",
            "-2.3",
            "-2.0",
            "-1.7",
            "-1.3",
            "-1.0",
            "-0.7",
            "-0.3",
            "0.0",
            "0.3",
            "0.7",
            "1.0",
            "1.3",
            "1.7",
            "2.0",
            "2.3",
            "2.7",
            "3.0",
          ],
        },
        flashcommandselfmode: {
          label: "Flash Command Self Mode",
          type: "choice",
          value: "TTL",
          choices: ["TTL", "Manual", "Off"],
        },
        flashcommandselfvalue: {
          label: "Flash Command Self Value",
          type: "choice",
          value: "Full",
          choices: [
            "Full",
            "1/1.3",
            "1/1.7",
            "1/2",
            "1/2.5",
            "1/3.2",
            "1/4",
            "1/5",
            "1/6.4",
            "1/8",
            "1/10",
            "1/13",
            "1/16",
            "1/20",
            "1/25",
            "1/32",
            "1/40",
            "1/50",
            "1/64",
            "1/80",
            "1/100",
            "1/128",
          ],
        },
        flashexposurecompensation: {
          label: "Flash Exposure Compensation",
          type: "range",
          value: 0,
          max: 1,
          min: -3,
          step: 0.3333333432674408,
        },
        flashmode: {
          label: "Flash Mode",
          type: "choice",
          value: "Auto",
          choices: [
            "Red-eye automatic",
            "Auto",
            "Rear Curtain Sync + Slow Sync",
          ],
        },
        flashmodemanualpower: {
          label: "Flash Mode Manual Power",
          type: "choice",
          value: "Full",
          choices: [
            "Full",
            "1/2",
            "1/4",
            "1/8",
            "1/16",
            "1/32",
            "Unknown value 0006",
            "Unknown value 0007",
            "Unknown value 0008",
            "Unknown value 0009",
            "Unknown value 000a",
            "Unknown value 000b",
            "Unknown value 000c",
            "Unknown value 000d",
            "Unknown value 000e",
            "Unknown value 000f",
            "Unknown value 0010",
            "Unknown value 0011",
            "Unknown value 0012",
            "Unknown value 0013",
            "Unknown value 0014",
            "Unknown value 0015",
          ],
        },
        flashshutterspeed: {
          label: "Flash Shutter Speed",
          type: "choice",
          value: "1/60s",
          choices: [
            "1/60s",
            "1/30s",
            "1/15s",
            "1/8s",
            "1/4s",
            "1/2s",
            "1s",
            "2s",
            "4s",
            "8s",
            "15s",
            "30s",
          ],
        },
        flashsign: {
          label: "Flash Sign",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        flashwhitebias: {
          label: "Flash White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        flexibleprogram: {
          label: "Flexible Program",
          type: "range",
          value: 0,
          max: 30,
          min: -30,
          step: 2,
        },
        flourescentwhitebias: {
          label: "Fluorescent White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        focallength: {
          label: "Focal Length",
          type: "range",
          value: 18,
          max: 105,
          min: 18,
          step: 0.009999999776482582,
        },
        focusareawrap: {
          label: "Focus Area Wrap",
          type: "choice",
          value: "On",
          choices: ["On", "Off"],
        },
        focusmetermode: {
          label: "Focus Metering Mode",
          type: "choice",
          value: "Single Area",
          choices: [
            "Multi-spot",
            "Single Area",
            "Closest Subject",
            "Group Dynamic",
          ],
        },
        focusmode: {
          label: "Focus Mode",
          type: "choice",
          value: "Manual",
          choices: ["Manual", "AF-S", "AF-C", "AF-A"],
        },
        focusmode2: {
          label: "Focus Mode 2",
          type: "choice",
          value: "MF (fixed)",
          choices: ["AF-S", "AF-C", "AF-A", "MF (fixed)", "MF (selection)"],
        },
        highisonr: {
          label: "High ISO Noise Reduction",
          type: "choice",
          value: "Normal",
          choices: ["Off", "Low", "Normal", "High"],
        },
        imagequality: {
          label: "Image Quality",
          type: "choice",
          value: "NEF (Raw)",
          choices: [
            "JPEG Basic",
            "JPEG Normal",
            "JPEG Fine",
            "NEF (Raw)",
            "NEF+Basic",
            "NEF+Normal",
            "NEF+Fine",
          ],
        },
        imagerotationflag: {
          label: "Image Rotation Flag",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        isoautohilimit: {
          label: "ISO Auto Hi Limit",
          type: "choice",
          value: "3200",
          choices: ["400", "800", "1600", "3200", "Hi 1"],
        },
        liveviewafmode: {
          label: "Live View AF Mode",
          type: "choice",
          value: "Wide-area AF",
          choices: ["Face-priority AF", "Wide-area AF", "Normal-area AF"],
        },
        liveviewimagezoomratio: {
          label: "Live View Image Zoom Ratio",
          type: "choice",
          value: "Entire Display",
          choices: [
            "Entire Display",
            "Unknown value 0001",
            "25%",
            "Unknown value 0003",
            "50%",
            "Unknown value 0005",
          ],
        },
        longexpnr: {
          label: "Long Exp Noise Reduction",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        maximumshots: {
          label: "Maximum Shots",
          type: "range",
          value: 8,
          max: 99,
          min: 0,
          step: 1,
        },
        minimumshutterspeed: {
          label: "Minimum Shutter Speed",
          type: "choice",
          value: "1/30",
          choices: [
            "1/2000",
            "1/1600",
            "1/1250",
            "1/1000",
            "1/800",
            "1/640",
            "1/500",
            "1/400",
            "1/320",
            "1/250",
            "1/200",
            "1/160",
            "1/125",
            "1/100",
            "1/80",
            "1/60",
            "1/50",
            "1/40",
            "1/30",
            "1/15",
            "1/8",
            "1/4",
            "1/2",
            "1",
          ],
        },
        modelflash: {
          label: "Modelling Flash",
          type: "choice",
          value: "On",
          choices: ["On", "Off"],
        },
        moviequality: {
          label: "Movie Quality",
          type: "choice",
          value: "1280x720",
          choices: ["320x216", "640x424", "1280x720"],
        },
        moviesound: {
          label: "Movie Sound",
          type: "choice",
          value: "On",
          choices: ["On", "Off"],
        },
        nikonflashmode: {
          label: "Nikon Flash Mode",
          type: "choice",
          value: "iTTL",
          choices: ["iTTL", "Manual", "Commander", "Repeating"],
        },
        nocfcardrelease: {
          label: "Release without CF card",
          type: "choice",
          value: "On",
          choices: ["On", "Off"],
        },
        remotetimeout: {
          label: "Remote Timeout",
          type: "choice",
          value: "1 minute",
          choices: ["1 minute", "5 minutes", "10 minutes", "15 minutes"],
        },
        reverseindicators: {
          label: "Reverse Indicators",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        selftimerdelay: {
          label: "Selftimer Delay",
          type: "choice",
          value: "10 seconds",
          choices: ["2 seconds", "5 seconds", "10 seconds", "20 seconds"],
        },
        shadewhitebias: {
          label: "Shady White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        shootingspeed: {
          label: "Continuous Shooting Speed Slow",
          type: "choice",
          value: "4 fps",
          choices: ["4 fps", "3 fps", "2 fps", "1 fps"],
        },
        shutterspeed: {
          label: "Shutter Speed",
          type: "choice",
          value: "0.0012s",
          choices: [
            "0.0002s",
            "0.0003s",
            "0.0004s",
            "0.0005s",
            "0.0006s",
            "0.0008s",
            "0.0010s",
            "0.0012s",
            "0.0015s",
            "0.0020s",
            "0.0025s",
            "0.0031s",
            "0.0040s",
            "0.0050s",
            "0.0062s",
            "0.0080s",
            "0.0100s",
            "0.0125s",
            "0.0166s",
            "0.0200s",
            "0.0250s",
            "0.0333s",
            "0.0400s",
            "0.0500s",
            "0.0666s",
            "0.0769s",
            "0.1000s",
            "0.1250s",
            "0.1666s",
            "0.2000s",
            "0.2500s",
            "0.3333s",
            "0.4000s",
            "0.5000s",
            "0.6250s",
            "0.7692s",
            "1.0000s",
            "1.3000s",
            "1.6000s",
            "2.0000s",
            "2.5000s",
            "3.0000s",
            "4.0000s",
            "5.0000s",
            "6.0000s",
            "8.0000s",
            "10.0000s",
            "13.0000s",
            "15.0000s",
            "20.0000s",
            "25.0000s",
            "30.0000s",
            "Bulb",
          ],
        },
        shutterspeed2: {
          label: "Shutter Speed 2",
          type: "choice",
          value: "1/800",
          choices: [
            "1/4000",
            "1/3200",
            "1/2500",
            "1/2000",
            "1/1600",
            "1/1250",
            "1/1000",
            "1/800",
            "1/640",
            "1/500",
            "1/400",
            "1/320",
            "1/250",
            "1/200",
            "1/160",
            "1/125",
            "1/100",
            "1/80",
            "1/60",
            "1/50",
            "1/40",
            "1/30",
            "1/25",
            "1/20",
            "1/15",
            "1/13",
            "1/10",
            "1/8",
            "1/6",
            "1/5",
            "1/4",
            "1/3",
            "10/25",
            "1/2",
            "10/16",
            "10/13",
            "1",
            "13/10",
            "16/10",
            "2",
            "25/10",
            "3",
            "4",
            "5",
            "6",
            "8",
            "10",
            "13",
            "15",
            "20",
            "25",
            "30",
            "Bulb",
          ],
        },
        tungstenwhitebias: {
          label: "Tungsten White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        viewfindergrid: {
          label: "Viewfinder Grid",
          type: "choice",
          value: "On",
          choices: ["On", "Off"],
        },
        wbbracketingpattern: {
          label: "WB Bracketing Pattern",
          type: "choice",
          value: "3 images (normal and 2 unders)",
          choices: [
            "2 images (normal and under)",
            "2 images (normal and over)",
            "3 images (normal and 2 unders)",
          ],
        },
        wbbracketingstep: {
          label: "WB Bracketing Step",
          type: "choice",
          value: "1 EV",
          choices: ["1 EV", "2 EV", "3 EV"],
        },
        wbpresetcomment1: {
          label: "WB Preset Comment 1",
          type: "string",
          value: "                                    ",
        },
        wbpresetcomment2: {
          label: "WB Preset Comment 2",
          type: "string",
          value: "                                    ",
        },
        wbpresetcomment3: {
          label: "WB Preset Comment 3",
          type: "string",
          value: "                                    ",
        },
        wbpresetcomment4: {
          label: "WB Preset Comment 4",
          type: "string",
          value: "                                    ",
        },
        whitebiaspreset0: {
          label: "White Balance Bias Preset 0",
          type: "string",
          value: "30212431",
        },
        whitebiaspreset1: {
          label: "White Balance Bias Preset 1",
          type: "string",
          value: "30212431",
        },
        whitebiaspreset2: {
          label: "White Balance Bias Preset 2",
          type: "string",
          value: "30212431",
        },
        whitebiaspreset3: {
          label: "White Balance Bias Preset 3",
          type: "string",
          value: "30212431",
        },
        whitebiaspreset4: {
          label: "White Balance Bias Preset 4",
          type: "string",
          value: "30212431",
        },
        whitebiaspresetno: {
          label: "White Balance Bias Preset Nr",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3"],
        },
      },
    },
    imgsettings: {
      type: "section",
      label: "Image Settings",
      children: {
        autoiso: {
          label: "Auto ISO",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        colorspace: {
          label: "Color Space",
          type: "choice",
          value: "AdobeRGB",
          choices: ["sRGB", "AdobeRGB"],
        },
        imagesize: {
          label: "Image Size",
          type: "choice",
          value: "2144x1424",
          choices: ["4288x2848", "3216x2136", "2144x1424"],
        },
        iso: {
          label: "ISO Speed",
          type: "choice",
          value: "640",
          choices: [
            "100",
            "125",
            "160",
            "200",
            "250",
            "320",
            "400",
            "500",
            "640",
            "800",
            "1000",
            "1250",
            "1600",
            "2000",
            "2500",
            "3200",
            "4000",
            "5000",
            "6400",
          ],
        },
        isoauto: {
          label: "ISO Auto",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        whitebalance: {
          label: "WhiteBalance",
          type: "choice",
          value: "Daylight",
          choices: [
            "Automatic",
            "Daylight",
            "Fluorescent",
            "Tungsten",
            "Flash",
            "Cloudy",
            "Shade",
            "Color Temperature",
            "Preset",
          ],
        },
      },
    },
    other: {
      type: "section",
      label: "Other PTP Device Properties",
      children: {
        5001: {
          label: "Battery Level",
          type: "choice",
          value: "80",
          choices: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42",
            "43",
            "44",
            "45",
            "46",
            "47",
            "48",
            "49",
            "50",
            "51",
            "52",
            "53",
            "54",
            "55",
            "56",
            "57",
            "58",
            "59",
            "60",
            "61",
            "62",
            "63",
            "64",
            "65",
            "66",
            "67",
            "68",
            "69",
            "70",
            "71",
            "72",
            "73",
            "74",
            "75",
            "76",
            "77",
            "78",
            "79",
            "80",
            "81",
            "82",
            "83",
            "84",
            "85",
            "86",
            "87",
            "88",
            "89",
            "90",
            "91",
            "92",
            "93",
            "94",
            "95",
            "96",
            "97",
            "98",
            "99",
            "100",
          ],
        },
        5003: {
          label: "Image Size",
          type: "choice",
          value: "2144x1424",
          choices: ["4288x2848", "3216x2136", "2144x1424"],
        },
        5004: {
          label: "Compression Setting",
          type: "choice",
          value: "4",
          choices: ["0", "1", "2", "4", "5", "6", "7"],
        },
        5005: {
          label: "White Balance",
          type: "choice",
          value: "4",
          choices: [
            "2",
            "4",
            "5",
            "6",
            "7",
            "32784",
            "32785",
            "32786",
            "32787",
          ],
        },
        5007: {
          label: "F-Number",
          type: "choice",
          value: "630",
          choices: [
            "350",
            "400",
            "450",
            "500",
            "560",
            "630",
            "710",
            "800",
            "900",
            "1000",
            "1100",
            "1300",
            "1400",
            "1600",
            "1800",
            "2000",
            "2200",
          ],
        },
        5008: {
          label: "Focal Length",
          type: "range",
          value: 1800,
          max: 10500,
          min: 1800,
          step: 1,
        },
        5010: {
          label: "Exposure Bias Compensation",
          type: "choice",
          value: "0",
          choices: [
            "-5000",
            "-4666",
            "-4333",
            "-4000",
            "-3666",
            "-3333",
            "-3000",
            "-2666",
            "-2333",
            "-2000",
            "-1666",
            "-1333",
            "-1000",
            "-666",
            "-333",
            "0",
            "333",
            "666",
            "1000",
            "1333",
            "1666",
            "2000",
            "2333",
            "2666",
            "3000",
            "3333",
            "3666",
            "4000",
            "4333",
            "4666",
            "5000",
          ],
        },
        5011: {
          label: "Date & Time",
          type: "string",
          value: "20220729T104511",
        },
        5013: {
          label: "Still Capture Mode",
          type: "choice",
          value: "1",
          choices: ["1", "2", "32784", "32785", "32788", "32789"],
        },
        5018: {
          label: "Burst Number",
          type: "choice",
          value: "1",
          choices: [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42",
            "43",
            "44",
            "45",
            "46",
            "47",
            "48",
            "49",
            "50",
            "51",
            "52",
            "53",
            "54",
            "55",
            "56",
            "57",
            "58",
            "59",
            "60",
            "61",
            "62",
            "63",
            "64",
            "65",
            "66",
            "67",
            "68",
            "69",
            "70",
            "71",
            "72",
            "73",
            "74",
            "75",
            "76",
            "77",
            "78",
            "79",
            "80",
            "81",
            "82",
            "83",
            "84",
            "85",
            "86",
            "87",
            "88",
            "89",
            "90",
            "91",
            "92",
            "93",
            "94",
            "95",
            "96",
            "97",
            "98",
            "99",
            "100",
          ],
        },
        "500a": {
          label: "Focus Mode",
          type: "choice",
          value: "1",
          choices: ["1", "32784", "32785", "32786"],
        },
        "500b": {
          label: "Exposure Metering Mode",
          type: "choice",
          value: "3",
          choices: ["2", "3", "4"],
        },
        "500c": {
          label: "Flash Mode",
          type: "choice",
          value: "32784",
          choices: ["4", "32784", "32786"],
        },
        "500d": {
          label: "Exposure Time",
          type: "choice",
          value: "12",
          choices: [
            "2",
            "3",
            "4",
            "5",
            "6",
            "8",
            "10",
            "12",
            "15",
            "20",
            "25",
            "31",
            "40",
            "50",
            "62",
            "80",
            "100",
            "125",
            "166",
            "200",
            "250",
            "333",
            "400",
            "500",
            "666",
            "769",
            "1000",
            "1250",
            "1666",
            "2000",
            "2500",
            "3333",
            "4000",
            "5000",
            "6250",
            "7692",
            "10000",
            "13000",
            "16000",
            "20000",
            "25000",
            "30000",
            "40000",
            "50000",
            "60000",
            "80000",
            "100000",
            "130000",
            "150000",
            "200000",
            "250000",
            "300000",
            "-1",
          ],
        },
        "500e": {
          label: "Exposure Program Mode",
          type: "choice",
          value: "1",
          choices: [
            "1",
            "2",
            "3",
            "4",
            "32784",
            "32785",
            "32786",
            "32787",
            "32788",
            "32789",
            "32790",
          ],
        },
        "500f": {
          label: "Exposure Index (film speed ISO)",
          type: "choice",
          value: "640",
          choices: [
            "100",
            "125",
            "160",
            "200",
            "250",
            "320",
            "400",
            "500",
            "640",
            "800",
            "1000",
            "1250",
            "1600",
            "2000",
            "2500",
            "3200",
            "4000",
            "5000",
            "6400",
          ],
        },
        "501c": {
          label: "Focus Metering Mode",
          type: "choice",
          value: "32784",
          choices: ["2", "32784", "32785", "32786"],
        },
        d017: {
          label: "Auto White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        d018: {
          label: "Tungsten White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        d019: {
          label: "Fluorescent White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        d01a: {
          label: "Daylight White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        d01b: {
          label: "Flash White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        d01c: {
          label: "Cloudy White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        d01d: {
          label: "Shady White Balance Bias",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        d01e: {
          label: "White Balance Colour Temperature",
          type: "choice",
          value: "20",
          choices: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
          ],
        },
        d01f: {
          label: "White Balance Preset Number",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3", "4"],
        },
        d020: {
          label: "White Balance Preset Name 0",
          type: "string",
          value: "                                    ",
        },
        d021: {
          label: "White Balance Preset Name 1",
          type: "string",
          value: "                                    ",
        },
        d022: {
          label: "White Balance Preset Name 2",
          type: "string",
          value: "                                    ",
        },
        d023: {
          label: "White Balance Preset Name 3",
          type: "string",
          value: "                                    ",
        },
        d024: {
          label: "White Balance Preset Name 4",
          type: "string",
          value: "                                    ",
        },
        d025: {
          label: "White Balance Preset Value 0",
          type: "string",
          value: "30212431",
        },
        d026: {
          label: "White Balance Preset Value 1",
          type: "string",
          value: "30212431",
        },
        d027: {
          label: "White Balance Preset Value 2",
          type: "string",
          value: "30212431",
        },
        d028: {
          label: "White Balance Preset Value 3",
          type: "string",
          value: "30212431",
        },
        d029: {
          label: "White Balance Preset Value 4",
          type: "string",
          value: "30212431",
        },
        d032: {
          label: "Color Space",
          type: "choice",
          value: "1",
          choices: ["0", "1"],
        },
        d045: {
          label: "Reset Menu Bank",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d04f: {
          label: "Focus Area Wrap",
          type: "choice",
          value: "1",
          choices: ["0", "1"],
        },
        d050: {
          label: "Vertical AF On",
          type: "choice",
          value: "7",
          choices: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
        },
        d052: {
          label: "Focus Area Zone",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d054: {
          label: "Auto ISO",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d056: {
          label: "Exposure Step",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2"],
        },
        d058: {
          label: "Exposure Compensation",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d059: {
          label: "Centre Weight Area",
          type: "choice",
          value: "1",
          choices: ["0", "1", "2"],
        },
        d05a: {
          label: "Exposure Base Matrix",
          type: "choice",
          value: "0",
          choices: [
            "-6",
            "-5",
            "-4",
            "-3",
            "-2",
            "-1",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
          ],
        },
        d05b: {
          label: "Exposure Base Center",
          type: "choice",
          value: "0",
          choices: [
            "-6",
            "-5",
            "-4",
            "-3",
            "-2",
            "-1",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
          ],
        },
        d05c: {
          label: "Exposure Base Spot",
          type: "choice",
          value: "0",
          choices: [
            "-6",
            "-5",
            "-4",
            "-3",
            "-2",
            "-1",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
          ],
        },
        d05d: {
          label: "Live View AF Area",
          type: "choice",
          value: "1",
          choices: ["0", "1", "2"],
        },
        d05e: {
          label: "Exposure Lock",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d05f: {
          label: "Focus Lock",
          type: "choice",
          value: "2",
          choices: ["0", "1", "2", "3", "4", "5"],
        },
        d062: {
          label: "Auto Meter Off Time",
          type: "choice",
          value: "2",
          choices: ["0", "1", "2", "3", "4", "5", "6", "7", "8"],
        },
        d063: {
          label: "Self Timer Delay",
          type: "choice",
          value: "2",
          choices: ["0", "1", "2", "3"],
        },
        d065: {
          label: "Img Conf Time",
          type: "choice",
          value: "1",
          choices: ["0", "1", "2", "3", "4", "5"],
        },
        d068: {
          label: "Shooting Speed",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3"],
        },
        d06a: {
          label: "Exposure delay mode",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d06b: {
          label: "Long Exposure Noise Reduction",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d06c: {
          label: "File Number Sequencing",
          type: "choice",
          value: "1",
          choices: ["0", "1", "2"],
        },
        d06f: {
          label: "LCD Illumination",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d070: {
          label: "High ISO noise reduction",
          type: "choice",
          value: "2",
          choices: ["0", "1", "2", "3"],
        },
        d071: {
          label: "On screen tips",
          type: "choice",
          value: "1",
          choices: ["0", "1"],
        },
        d075: {
          label: "Flash Shutter Speed",
          type: "choice",
          value: "0",
          choices: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
          ],
        },
        d077: {
          label: "Modeling Flash",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d078: {
          label: "Bracket Set",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3", "4"],
        },
        d07a: {
          label: "Bracket Order",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d080: {
          label: "Center Button Shooting Mode",
          type: "choice",
          value: "1",
          choices: ["0", "1", "2"],
        },
        d084: {
          label: "Assign Func. Button",
          type: "choice",
          value: "3",
          choices: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
        },
        d085: {
          label: "Customise Command Dials",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d086: {
          label: "Reverse Command Dial",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d088: {
          label: "Menus and Playback",
          type: "choice",
          value: "1",
          choices: ["0", "1", "2"],
        },
        d08a: {
          label: "No CF Card Release",
          type: "choice",
          value: "1",
          choices: ["0", "1"],
        },
        d090: {
          label: "Image Comment String",
          type: "string",
          value: "B. COQUELLE                         ",
        },
        d091: {
          label: "Image Comment Enable",
          type: "choice",
          value: "1",
          choices: ["0", "1"],
        },
        d092: {
          label: "Image Rotation",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d0a0: {
          label: "Movie Screen Size",
          type: "choice",
          value: "2",
          choices: ["0", "1", "2"],
        },
        d0a1: {
          label: "Movie Voice",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d0c0: {
          label: "Bracketing Enable",
          type: "choice",
          value: "1",
          choices: ["0", "1"],
        },
        d0c1: {
          label: "Exposure Bracketing Step",
          type: "choice",
          value: "7",
          choices: ["0", "1", "2", "3", "4", "5", "6", "7"],
        },
        d0c2: {
          label: "Exposure Bracketing Program",
          type: "choice",
          value: "2",
          choices: ["0", "1", "2"],
        },
        d0c3: {
          label: "Auto Exposure Bracket Count",
          type: "choice",
          value: "1",
          choices: ["1", "2", "3"],
        },
        d0c4: {
          label: "White Balance Bracket Step",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2"],
        },
        d0c5: {
          label: "White Balance Bracket Program",
          type: "choice",
          value: "2",
          choices: ["0", "1", "2"],
        },
        d0e0: {
          label: "Lens ID",
          type: "string",
          value: "158",
        },
        d0e1: {
          label: "Lens Sort",
          type: "choice",
          value: "1",
          choices: ["0", "1"],
        },
        d0e2: {
          label: "Lens Type",
          type: "string",
          value: "15",
        },
        d0e3: {
          label: "Min. Focal Length",
          type: "string",
          value: "1800",
        },
        d0e4: {
          label: "Max. Focal Length",
          type: "string",
          value: "10500",
        },
        d0e5: {
          label: "Max. Aperture at Min. Focal Length",
          type: "string",
          value: "350",
        },
        d0e6: {
          label: "Max. Aperture at Max. Focal Length",
          type: "string",
          value: "560",
        },
        d0f0: {
          label: "Finder ISO Display",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2"],
        },
        d0f2: {
          label: "Auto Off Photo",
          type: "choice",
          value: "1",
          choices: ["0", "1", "2", "3", "4", "5"],
        },
        d0f3: {
          label: "Auto Off Menu",
          type: "choice",
          value: "2",
          choices: ["0", "1", "2", "3", "4", "5"],
        },
        d0f4: {
          label: "Auto Off Info",
          type: "choice",
          value: "1",
          choices: ["0", "1", "2", "3", "4", "5"],
        },
        d0f5: {
          label: "Self Timer Shot Number",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3", "4", "5", "6", "7", "8"],
        },
        d100: {
          label: "Nikon Exposure Time",
          type: "choice",
          value: "66336",
          choices: [
            "69536",
            "68736",
            "68036",
            "67536",
            "67136",
            "66786",
            "66536",
            "66336",
            "66176",
            "66036",
            "65936",
            "65856",
            "65786",
            "65736",
            "65696",
            "65661",
            "65636",
            "65616",
            "65596",
            "65586",
            "65576",
            "65566",
            "65561",
            "65556",
            "65551",
            "65549",
            "65546",
            "65544",
            "65542",
            "65541",
            "65540",
            "65539",
            "655385",
            "65538",
            "655376",
            "655373",
            "65537",
            "851978",
            "1048586",
            "131073",
            "1638410",
            "196609",
            "262145",
            "327681",
            "393217",
            "524289",
            "655361",
            "851969",
            "983041",
            "1310721",
            "1638401",
            "1966081",
            "-1",
          ],
        },
        d101: {
          label: "AC Power",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d102: {
          label: "Warning Status",
          type: "string",
          value: "0",
        },
        d103: {
          label: "Maximum Shots",
          type: "choice",
          value: "8",
          choices: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42",
            "43",
            "44",
            "45",
            "46",
            "47",
            "48",
            "49",
            "50",
            "51",
            "52",
            "53",
            "54",
            "55",
            "56",
            "57",
            "58",
            "59",
            "60",
            "61",
            "62",
            "63",
            "64",
            "65",
            "66",
            "67",
            "68",
            "69",
            "70",
            "71",
            "72",
            "73",
            "74",
            "75",
            "76",
            "77",
            "78",
            "79",
            "80",
            "81",
            "82",
            "83",
            "84",
            "85",
            "86",
            "87",
            "88",
            "89",
            "90",
            "91",
            "92",
            "93",
            "94",
            "95",
            "96",
            "97",
            "98",
            "99",
          ],
        },
        d104: {
          label: "AF Locked",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d105: {
          label: "AE Locked",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d106: {
          label: "FV Locked",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d108: {
          label: "Active AF Sensor",
          type: "choice",
          value: "1",
          choices: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"],
        },
        d109: {
          label: "Flexible Program",
          type: "range",
          value: 0,
          max: 30,
          min: -30,
          step: 2,
        },
        d10b: {
          label: "Recording Media",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d10c: {
          label: "USB Speed",
          type: "choice",
          value: "1",
          choices: ["0", "1"],
        },
        d10d: {
          label: "CCD Serial Number",
          type: "string",
          value: "4290737         $   ",
        },
        d10e: {
          label: "Camera Orientation",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3"],
        },
        d114: {
          label: "Illum Setting",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d120: {
          label: "External Flash Attached",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d121: {
          label: "External Flash Status",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d122: {
          label: "External Flash Sort",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3"],
        },
        d124: {
          label: "External Flash Compensation",
          type: "choice",
          value: "0",
          choices: [
            "-18",
            "-17",
            "-16",
            "-15",
            "-14",
            "-13",
            "-12",
            "-11",
            "-10",
            "-9",
            "-8",
            "-7",
            "-6",
            "-5",
            "-4",
            "-3",
            "-2",
            "-1",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
          ],
        },
        d125: {
          label: "External Flash Mode",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3", "4", "5", "6", "7"],
        },
        d126: {
          label: "Flash Exposure Compensation",
          type: "range",
          value: 0,
          max: 6,
          min: -18,
          step: 2,
        },
        d14e: {
          label: "Active D-Lighting",
          type: "choice",
          value: "4",
          choices: ["0", "1", "2", "3", "4", "5"],
        },
        d14f: {
          label: "Fluorescent Type",
          type: "choice",
          value: "3",
          choices: ["0", "1", "2", "3", "4", "5", "6"],
        },
        d150: {
          label: "Tune Colour Temperature",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        d151: {
          label: "Tune Preset 0",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        d152: {
          label: "Tune Preset 1",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        d153: {
          label: "Tune Preset 2",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        d154: {
          label: "Tune Preset 3",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        d155: {
          label: "Tune Preset 4",
          type: "range",
          value: 84,
          max: 168,
          min: 0,
          step: 1,
        },
        d160: {
          label: "AF Beep Mode",
          type: "choice",
          value: "1",
          choices: ["0", "1"],
        },
        d161: {
          label: "Autofocus Mode",
          type: "choice",
          value: "3",
          choices: ["0", "1", "2", "3", "4"],
        },
        d163: {
          label: "AF Assist Lamp",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d164: {
          label: "Auto ISO P/A/DVP Setting",
          type: "choice",
          value: "18",
          choices: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
          ],
        },
        d166: {
          label: "AF Area Illumination",
          type: "choice",
          value: "2",
          choices: ["0", "1", "2"],
        },
        d167: {
          label: "Flash Mode",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3"],
        },
        d169: {
          label: "Flash Sign",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d16a: {
          label: "ISO Auto",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d16b: {
          label: "Remote Timeout",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3"],
        },
        d16c: {
          label: "Viewfinder Grid Display",
          type: "choice",
          value: "1",
          choices: ["0", "1"],
        },
        d16d: {
          label: "Flash Mode Manual Power",
          type: "choice",
          value: "0",
          choices: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
          ],
        },
        d16f: {
          label: "Auto FP",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d181: {
          label: "Warning Display",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d182: {
          label: "Battery Cell Kind",
          type: "choice",
          value: "1",
          choices: ["0", "1", "2", "3"],
        },
        d183: {
          label: "ISO Auto High Limit",
          type: "choice",
          value: "3",
          choices: ["0", "1", "2", "3", "4"],
        },
        d187: {
          label: "Info Disp Setting",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2"],
        },
        d18d: {
          label: "Indicator Display",
          type: "choice",
          value: "1",
          choices: ["0", "1"],
        },
        d1a2: {
          label: "Live View Status",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d1a3: {
          label: "Live View Image Zoom Ratio",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3", "4", "5"],
        },
        d1a4: {
          label: "Live View Prohibit Condition",
          type: "string",
          value: "1",
        },
        d1b0: {
          label: "Exposure Display Status",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3", "4", "5", "6", "7", "8"],
        },
        d1b1: {
          label: "Exposure Indicate Status",
          type: "choice",
          value: "-56",
          choices: [
            "-60",
            "-59",
            "-58",
            "-57",
            "-56",
            "-55",
            "-54",
            "-53",
            "-52",
            "-51",
            "-50",
            "-49",
            "-48",
            "-47",
            "-46",
            "-45",
            "-44",
            "-43",
            "-42",
            "-41",
            "-40",
            "-39",
            "-38",
            "-37",
            "-36",
            "-35",
            "-34",
            "-33",
            "-32",
            "-31",
            "-30",
            "-29",
            "-28",
            "-27",
            "-26",
            "-25",
            "-24",
            "-23",
            "-22",
            "-21",
            "-20",
            "-19",
            "-18",
            "-17",
            "-16",
            "-15",
            "-14",
            "-13",
            "-12",
            "-11",
            "-10",
            "-9",
            "-8",
            "-7",
            "-6",
            "-5",
            "-4",
            "-3",
            "-2",
            "-1",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42",
            "43",
            "44",
            "45",
            "46",
            "47",
            "48",
            "49",
            "50",
            "51",
            "52",
            "53",
            "54",
            "55",
            "56",
            "57",
            "58",
            "59",
            "60",
          ],
        },
        d1b2: {
          label: "Info Display Error Status",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d1b3: {
          label: "Exposure Indicate Lightup",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d1c0: {
          label: "Flash Open",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d1c1: {
          label: "Flash Charged",
          type: "choice",
          value: "0",
          choices: ["0", "1"],
        },
        d1d0: {
          label: "Flash MRepeat Value",
          type: "choice",
          value: "3",
          choices: ["0", "1", "2", "3", "4", "5"],
        },
        d1d1: {
          label: "Flash MRepeat Count",
          type: "choice",
          value: "8",
          choices: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
        },
        d1d2: {
          label: "Flash MRepeat Interval",
          type: "choice",
          value: "9",
          choices: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
          ],
        },
        d1d3: {
          label: "Flash Command Channel",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3"],
        },
        d1d4: {
          label: "Flash Command Self Mode",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2"],
        },
        d1d5: {
          label: "Flash Command Self Compensation",
          type: "choice",
          value: "9",
          choices: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
          ],
        },
        d1d6: {
          label: "Flash Command Self Value",
          type: "choice",
          value: "0",
          choices: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
          ],
        },
        d1d7: {
          label: "Flash Command A Mode",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3"],
        },
        d1d8: {
          label: "Flash Command A Compensation",
          type: "choice",
          value: "9",
          choices: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
          ],
        },
        d1d9: {
          label: "Flash Command A Value",
          type: "choice",
          value: "0",
          choices: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
          ],
        },
        d1da: {
          label: "Flash Command B Mode",
          type: "choice",
          value: "0",
          choices: ["0", "1", "2", "3"],
        },
        d1db: {
          label: "Flash Command B Compensation",
          type: "choice",
          value: "9",
          choices: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
          ],
        },
        d1dc: {
          label: "Flash Command B Value",
          type: "choice",
          value: "0",
          choices: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
          ],
        },
        d200: {
          label: "Active Pic Ctrl Item",
          type: "choice",
          value: "1",
          choices: [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "101",
            "102",
            "103",
            "104",
            "201",
            "202",
            "203",
            "204",
            "205",
            "206",
            "207",
            "208",
            "209",
          ],
        },
        d201: {
          label: "Change Pic Ctrl Item",
          type: "choice",
          value: "0",
          choices: [],
        },
        d406: {
          label: "PTP Property 0xd406",
          type: "string",
          value: "Windows/6.0.5330.0 MTPClassDriver/6.0.5330.0",
        },
        d407: {
          label: "PTP Property 0xd407",
          type: "string",
          value: "1",
        },
      },
    },
    settings: {
      type: "section",
      label: "Camera Settings",
      children: {
        autofocus: {
          label: "Autofocus",
          type: "choice",
          value: "On",
          choices: ["On", "Off"],
        },
        capturetarget: {
          label: "Capture Target",
          type: "choice",
          value: "Internal RAM",
          choices: ["Internal RAM", "Memory card"],
        },
        ccdnumber: {
          label: "CCD Number",
          type: "string",
          value: "4290737         $   ",
        },
        datetime: {
          label: "Camera Date and Time",
          type: "date",
          value: "2022-07-29T08:45:11.000Z",
        },
        fastfs: {
          label: "Fast Filesystem",
          type: "toggle",
          value: 1,
        },
        imagecomment: {
          label: "Image Comment",
          type: "string",
          value: "B. COQUELLE                         ",
        },
        imagecommentenable: {
          label: "Enable Image Comment",
          type: "choice",
          value: "On",
          choices: ["On", "Off"],
        },
        menusandplayback: {
          label: "Menus and Playback",
          type: "choice",
          value: "On",
          choices: ["Off", "On", "On (image review excluded)"],
        },
        meterofftime: {
          label: "Meter Off Time",
          type: "choice",
          value: "8 seconds",
          choices: [
            "4 seconds",
            "6 seconds",
            "8 seconds",
            "16 seconds",
            "30 seconds",
            "1 minute",
            "5 minutes",
            "10 minutes",
            "30 minutes",
          ],
        },
        recordingmedia: {
          label: "Recording Media",
          type: "choice",
          value: "Card",
          choices: ["Card", "SDRAM"],
        },
        reversedial: {
          label: "Reverse Command Dial",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        thumbsize: {
          label: "Thumb Size",
          type: "choice",
          value: "",
          choices: ["normal", "large"],
        },
      },
    },
    status: {
      type: "section",
      label: "Camera Status Information",
      children: {
        acpower: {
          label: "AC Power",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        aelocked: {
          label: "AE Locked",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        aflocked: {
          label: "AF Locked",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        apertureatmaxfocallength: {
          label: "Maximum Aperture at Focal Length Maximum",
          type: "string",
          value: "6",
        },
        apertureatminfocallength: {
          label: "Maximum Aperture at Focal Length Minimum",
          type: "string",
          value: "4",
        },
        batterylevel: {
          label: "Battery Level",
          type: "string",
          value: "80%",
        },
        cameramodel: {
          label: "Camera Model",
          type: "string",
          value: "D90",
        },
        deviceversion: {
          label: "Device Version",
          type: "string",
          value: "V1.01",
        },
        externalflash: {
          label: "External Flash",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        flashcharged: {
          label: "Flash Charged",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        flashopen: {
          label: "Flash Open",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        fvlocked: {
          label: "FV Locked",
          type: "choice",
          value: "Off",
          choices: ["On", "Off"],
        },
        lensname: {
          label: "Lens Name",
          type: "choice",
          value: "Unknown value 009e",
          choices: ["Unknown value 009e"],
        },
        lightmeter: {
          label: "Light Meter",
          type: "range",
          value: -56,
          max: 60,
          min: -60,
          step: 1,
        },
        liveviewprohibit: {
          label: "Liveview Prohibit Condition",
          type: "string",
          value: "Movie prohibit conditions: unhandled bitmask 1",
        },
        lowlight: {
          label: "Low Light",
          type: "range",
          value: 0,
          max: 8,
          min: 0,
          step: 1,
        },
        manufacturer: {
          label: "Camera Manufacturer",
          type: "string",
          value: "Nikon Corporation",
        },
        maxfocallength: {
          label: "Focal Length Maximum",
          type: "string",
          value: "105 mm",
        },
        minfocallength: {
          label: "Focal Length Minimum",
          type: "string",
          value: "18 mm",
        },
        orientation: {
          label: "Camera Orientation",
          type: "choice",
          value: "0'",
          choices: ["0'", "270'", "90'", "180'"],
        },
        serialnumber: {
          label: "Serial Number",
          type: "string",
          value: "6342316",
        },
        vendorextension: {
          label: "Vendor Extension",
          type: "string",
          value: "microsoft.com: 1.0",
        },
      },
    },
  },
};
